# Generated by Django 3.2 on 2021-04-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CcrFormnew',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Requestor', models.CharField(max_length=100)),
                ('Role', models.CharField(max_length=100)),
            ],
        ),
    ]
